name: Skywars
version: 1.0
author: Groot_23
main: me.groot_23.skywars.Main
api-version: 1.14
depend: [MinG]

commands:
  swjoin:
    description: Trete einem Skywars Spiel bei
    usage: /<command>

  swleave:
    description: Verlasse die Lobby
    usage: /<command>

  swedit:
    description: Bearbeite eine Skywars Welt
    usage: /<command> <world>

  swmaps:
    description: Verwalte die Skywarsmaps
    usage: /<command> [register | list | remove | set] <world | group>

  swupdate:
    description: Lese die Config neu ein
    usage: /<command>

  swchest:
    description: Platziere eine Skywars Truhe
    usage: /<command> <chest>

  swspawns:
    description: Verwalte die Spawns einer Skywars Welt
    usage: /<command> [add | show]

  swset:
    description: Bearbeite die Einstellungen von skywars
    usage: /<command> <option> <value>
    
  swkits:
    description: Bearbeite Kits
    usage: /<command> [list | create | delete | set] <kit>
    
  swlang:
    description: Bearbeite Sprachwerte
    usage: /<command> <language> <key> <value>
    
  swstart:
    description: Starte ein Spiel früher
    usage: /<command>
    
  swforce:
    description: Zwinge einen Spieler dazu, einen Befehl auszuführen
    usage: /<command> <player> <other command>
    
  toggleSpectate:
    description: Wechsle zu Spectator Modus oder verlasse ihn. DEBUG ONLY!
    usage: /<command>
    

permissions:
  skywars.*:
    default: false